server:
  port: 8088
  

spring:

# BANCO MYSQL
  jpa:
    database: mysql
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    
  
  datasource:
    url: jdbc:mysql://localhost/oxp-api?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root


  flyway:
    enabled: false
    locations: classpath:db/migration/mysql